name: Jest Unit Test
on: 
  push: 
    branches: 
      - develop

jobs: 
  Jest: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Run Tests
        run: | 
          npm install
          npm run test:ci