name: Jest Unit Test
on: 
  push: 
    branches: 
      - develop

  pull_request:
    branches:
      - master

jobs: 
  run_jest: 
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps: 
      - uses: actions/checkout@v1
      - name: Install Packages
        run: npm install
      - name: Run jest 
        run: npm run test:ci